version: "2"
services:
  nginx:
    build: ./docker/nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    group_add:
      - www-data
    volumes:
      - "./docker/nginx/etc/nginx:/etc/nginx/conf.d"
      - "./docker/nginx/etc/ssl/certs:/etc/ssl/certs"
    volumes_from:
      - php
    networks:
      - default
  php:
    build: ./docker/php-fpm
    restart: always
    group_add:
      - www-data
    volumes:
      - "/rene/projects/tumblrposts/app:/var/www"
      - "/rene/projects/tumblrposts/docker/var/log:/var/log"
    networks:
      - default
